# Generated by Django 4.2.3 on 2023-08-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('display_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('icon_url', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=100)),
                ('post_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to='api.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('img_url', models.CharField(default='https://static.djangoproject.com/img/icon-touch.e4872c4da341.png', max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.post')),
            ],
            options={
                'unique_together': {('link', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.post')),
            ],
            options={
                'unique_together': {('keyword', 'post')},
            },
        ),
    ]
