# Generated by Django 4.2.3 on 2023-08-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_info_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
