# Generated by Django 4.2.3 on 2023-08-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_date',
            new_name='created',
        ),
    ]
