# Generated by Django 4.2.3 on 2023-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_anonymous_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=120),
        ),
    ]
