# Generated by Django 4.2.3 on 2023-08-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='post_sernder',
        ),
    ]
