# Generated by Django 4.2.3 on 2023-08-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_uid_post_post_sernder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=300)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
    ]
