# Generated by Django 4.2.3 on 2023-08-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_provider_remove_post_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_sernder',
            new_name='post_sender',
        ),
    ]
