# Generated by Django 4.2.3 on 2023-08-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_post_sernder_post_post_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.post'),
        ),
    ]
