# Generated by Django 4.2.3 on 2023-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_post_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='img_url',
            field=models.CharField(default='https://static.djangoproject.com/img/icon-touch.e4872c4da341.png', max_length=300),
        ),
    ]
