# Generated by Django 4.2.3 on 2023-08-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_link_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=300)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.post')),
            ],
        ),
    ]
