# Generated by Django 4.2.3 on 2023-08-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='created',
        ),
        migrations.RemoveField(
            model_name='link',
            name='created',
        ),
    ]
