# Generated by Django 4.2.3 on 2023-08-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_keyword_created_remove_link_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('keyword', 'post_id')},
        ),
    ]
