# Generated by Django 4.2.3 on 2023-08-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0014_alter_keyword_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to='socialaccount.socialaccount'),
        ),
    ]
