# Generated by Django 4.2.3 on 2023-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_keyword_keyword_id_alter_link_link_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
