# Generated by Django 4.2.3 on 2023-08-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
