# Generated by Django 4.2.3 on 2023-08-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_keyword_keyword_id_alter_link_link_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set(),
        ),
    ]
