# Generated by Django 4.2.3 on 2023-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_link_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
