# Generated by Django 4.2.3 on 2023-08-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_keyword_keyword_id_alter_link_link_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='post_id',
            new_name='post',
        ),
    ]
