# Generated by Django 4.2.3 on 2023-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_post_id_keyword_post_rename_post_id_link_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
