# Generated by Django 4.2.3 on 2023-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='icon_image',
            field=models.CharField(default='no_image.png', max_length=30),
        ),
    ]
