# Generated by Django 4.2.3 on 2023-08-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0026_alter_userinfo_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
                ('display_name', models.CharField(max_length=20)),
                ('icon_image', models.CharField(default='no_image.png', max_length=30)),
            ],
            bases=('socialaccount.socialaccount',),
        ),
    ]
