# Generated by Django 4.2.3 on 2023-08-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0027_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='display_name',
            field=models.CharField(default='guest', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='socialaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
