# Generated by Django 4.2.3 on 2023-08-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0028_remove_userinfo_name_remove_userinfo_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='SocialAccount',
        ),
    ]
