# Generated by Django 4.2.3 on 2023-08-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0029_rename_userinfo_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
                ('display_name', models.CharField(default='guest', max_length=20)),
                ('icon_image', models.CharField(default='no_image.png', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
