# Generated by Django 4.2.3 on 2023-08-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userinfo_delete_socialaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
