# Generated by Django 4.2.3 on 2023-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('api', '0032_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
                ('display_name', models.CharField(max_length=30)),
                ('icon_url', models.CharField(max_length=100)),
            ],
        ),
    ]
